### ISSUE TITLE
Any example about how to draw grouped barchart with separated columns (Like readme grouped barchart image))?

### ISSUE THREAD

**Issue by evandrosimenes** [bulubuloa/Ultimate-Xamarin-Forms-KIT#26]
Any example about how to draw grouped barchart with separated columns (Like readme grouped barchart image))?

**Comment by leroygumede** [comment]
@evandrosimenes Did you find a solution?

**Comment by evandrosimenes** [comment]
@leroygumede no... i tried many ways hoping it worked, but without success... then i abandoned this plugin

**Comment by acaliaro** [comment]
I have the same problem... @bulubuloa there is a solution for this?

**Comment by TSerra-PT** [comment]
Did anyone find other nuget that grouped barchart with separated columns?

**Comment by leroygumede** [comment]
There isn't, spent days looking, the only option is getting a paid version or building your own wrapper
