### ISSUE TITLE
This nuget does not work on iOS

### ISSUE THREAD

**Issue by jonthomaswoods** [bulubuloa/Ultimate-Xamarin-Forms-KIT#36]
I just spent a week working on trying to deploy my app to the iOS store.  The Swift4 package does not allow you to sign the build and it will not deliver.

**Comment by WiproSarthak** [comment]
Have you found any workaround for this ?

**Comment by jonthomaswoods** [comment]
I found no workaround for this so found a different nuget to use.

https://github.com/dotnet-ad/Microcharts
