### ISSUE TITLE
Hide Legend

### ISSUE THREAD

**Issue by autosoftmultimedia** [bulubuloa/Ultimate-Xamarin-Forms-KIT#5]
How can I hide the legend of a chart?

In Android I can simply do this
Legend legend = chart.getLegend();
legend.setEnabled(false);

but in Xamarin.Forms?

**Comment by bulubuloa** [comment]
Legend has added in newest version (2.3.2)

https://www.nuget.org/packages/UltimateXF/2.3.2

**Comment by manueljscruz** [comment]
Is the Legend related to the values that show up on top of each entry?
How do i turn those values off?

**Comment by Kotichalla** [comment]
is there any update related to this issue in terms of solution
